import { execFileSync } from 'node:child_process';
import { copyFile, mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, extname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import postcss from 'postcss';
import sharp from 'sharp';

import { prepareAstryxTheme } from './prepareAstryxTheme.mjs';

// The bundler applies `postcss-rem-to-pixel` (see postcss.config.mjs) to regular CSS
// entries, but the shadow stylesheet ships as a raw .txt asset outside that pipeline.
// rem inside a shadow tree resolves against the host page's root font size, which
// arbitrary pages override, so the shadow styles are converted here the same way.
const remUnitPattern = /(-?\d*\.?\d+)rem\b/g;
const remRootValue = 16;
const remUnitPrecision = 5;

function convertRemToPixel(css, from) {
  const root = postcss.parse(css, { from });
  root.walkDecls((decl) => {
    if (!decl.value.includes('rem')) return;
    decl.value = decl.value.replace(remUnitPattern, (_match, value) => {
      const pixels = Number.parseFloat(value) * remRootValue;
      return `${Number(pixels.toFixed(remUnitPrecision))}px`;
    });
  });
  return root.toString();
}

const scriptsDirectory = dirname(fileURLToPath(import.meta.url));
const projectDirectory = resolve(scriptsDirectory, '..');
const localRequire = createRequire(import.meta.url);
const packagePath = resolve(projectDirectory, 'package.json');
const manifestPath = resolve(projectDirectory, 'src/manifest.json');
const logoSourcePath = resolve(projectDirectory, 'src/res/logo.svg');
const publicStaticDirectory = resolve(projectDirectory, 'public/static');
const manifestStaticDirectory = resolve(projectDirectory, 'src/static');
const thirdpartySourceDirectory = resolve(projectDirectory, 'thirdparty/bergamot/build');
const thirdpartyStagingDirectory = resolve(
  projectDirectory,
  'public/thirdparty/bergamot',
);
const formatterBinary = resolve(projectDirectory, 'node_modules/.bin/oxfmt');
const contentShadowStylesPath = resolve(projectDirectory, 'src/content-shadow.css.txt');
const contentShadowStylesFormatPath = resolve(projectDirectory, 'src/content-shadow.css');
const contentShadowStyleSources = [
  localRequire.resolve('@astryxdesign/core/reset.css'),
  localRequire.resolve('@astryxdesign/core/astryx.css'),
  resolve(projectDirectory, 'src/themes/astryx-vivid.css'),
  resolve(projectDirectory, 'src/themes/legacy-compat.css'),
  resolve(projectDirectory, 'src/themes/stylex.css'),
];
const contentShadowStylesHeader = `/* stylelint-disable */
/*
 * Generated by scripts/prepareExtensionAssets.mjs for content-script Shadow DOM.
 * Do not edit manually; run \`npm run prepare:extension\` to regenerate.
 */
`;
const requiredThirdpartyAssets = [
  'bergamot-translator-worker.js',
  'bergamot-translator-worker.wasm',
  'translator.worker.js',
];

async function readJson(path) {
  return JSON.parse(await readFile(path, 'utf8'));
}

async function getThirdpartyAssets() {
  let entries;

  try {
    entries = await readdir(thirdpartySourceDirectory, { withFileTypes: true });
  } catch (error) {
    if (error.code === 'ENOENT' || error.code === 'ENOTDIR') {
      return [];
    }

    throw error;
  }

  return entries
    .filter((entry) => entry.isFile() && ['.js', '.wasm'].includes(extname(entry.name)))
    .map((entry) => entry.name)
    .sort();
}
async function prepareContentShadowStyles() {
  const sources = await Promise.all(
    contentShadowStyleSources.map(async (path) => ({
      path,
      css: await readFile(path, 'utf8'),
    })),
  );
  const unformattedContent =
    contentShadowStylesHeader +
    sources
      .map(({ path, css }) => {
        const label = relative(projectDirectory, path);
        return `/* ${label} */\n${css.trim()}`;
      })
      .join('\n\n') +
    '\n';
  const content = convertRemToPixel(
    execFileSync(formatterBinary, [`--stdin-filepath=${contentShadowStylesFormatPath}`], {
      cwd: projectDirectory,
      encoding: 'utf8',
      input: unformattedContent,
      stdio: ['pipe', 'pipe', 'inherit'],
    }),
    contentShadowStylesFormatPath,
  );

  let current = '';
  try {
    current = await readFile(contentShadowStylesPath, 'utf8');
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }

  if (current !== content) {
    await writeFile(contentShadowStylesPath, content, 'utf8');
  }
}

export async function prepareExtensionAssets({ requireThirdparty = false } = {}) {
  await prepareAstryxTheme();
  await prepareContentShadowStyles();

  const [packageJson, manifest] = await Promise.all([
    readJson(packagePath),
    readJson(manifestPath),
  ]);

  if (packageJson.version !== manifest.version) {
    throw new Error(
      `Version mismatch: package.json is ${JSON.stringify(packageJson.version)}, ` +
        `but src/manifest.json is ${JSON.stringify(manifest.version)}`,
    );
  }

  await Promise.all([
    mkdir(publicStaticDirectory, { recursive: true }),
    mkdir(manifestStaticDirectory, { recursive: true }),
  ]);
  await Promise.all([
    copyFile(logoSourcePath, resolve(publicStaticDirectory, 'logo.svg')),
    sharp(logoSourcePath)
      .resize(128, 128)
      .png()
      .toFile(resolve(manifestStaticDirectory, 'logo.png')),
  ]);

  const thirdpartyAssets = await getThirdpartyAssets();
  const missingThirdpartyAssets = requiredThirdpartyAssets.filter(
    (filename) => !thirdpartyAssets.includes(filename),
  );

  // This is the generated staging directory. Do not widen this removal to one
  // of its parents: public/ may contain source-controlled extension assets.
  await rm(thirdpartyStagingDirectory, { recursive: true, force: true });

  if (missingThirdpartyAssets.length > 0) {
    const message =
      `Bergamot build artifacts are missing from ${thirdpartySourceDirectory}: ` +
      `${missingThirdpartyAssets.join(', ')}. ` +
      'Build thirdparty/bergamot before creating a release.';

    if (requireThirdparty) {
      throw new Error(message);
    }

    console.warn(message);
  }

  if (thirdpartyAssets.length === 0) {
    return;
  }

  await mkdir(thirdpartyStagingDirectory, { recursive: true });
  await Promise.all(
    thirdpartyAssets.map((filename) =>
      copyFile(
        resolve(thirdpartySourceDirectory, filename),
        resolve(thirdpartyStagingDirectory, filename),
      ),
    ),
  );
}

export default prepareExtensionAssets;

const isMainModule =
  process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isMainModule) {
  const argumentsList = process.argv.slice(2);
  const unknownArguments = argumentsList.filter(
    (argument) => argument !== '--require-thirdparty',
  );

  if (unknownArguments.length > 0) {
    console.error(
      `Unknown argument${unknownArguments.length === 1 ? '' : 's'}: ${unknownArguments.join(', ')}`,
    );
    process.exitCode = 1;
  } else {
    prepareExtensionAssets({
      requireThirdparty: argumentsList.includes('--require-thirdparty'),
    }).catch((error) => {
      console.error(error);
      process.exitCode = 1;
    });
  }
}
