import { execFileSync } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectDirectory = resolve(scriptDirectory, '..');
const generatedThemePath = resolve(projectDirectory, 'src/themes/astryx-vivid.css');
const localRequire = createRequire(import.meta.url);
const builtThemePath = resolve(projectDirectory, 'src/themes/vivid/vivid.css');
const scopeOpening = '@scope ([data-astryx-theme="vivid"]) to ([data-astryx-theme]) {';
const scopeSelector = '[data-astryx-theme="vivid"]';
const generatedHeader = `/*
 * Generated by scripts/prepareAstryxTheme.mjs from src/themes/vivid/vivid.css,
 * which is built by \`astryx theme build\` from src/themes/vividTheme.ts.
 *
 * Extension.js currently removes CSS scope blocks while compiling extension CSS.
 * This compatibility copy expands the vivid scope into descendant selectors
 * so production artifacts retain the selected Astryx theme.
 *
 * Do not edit manually; run \`npm run prepare:extension\` to regenerate.
 */
`;

function braceDelta(line) {
  return line.split('{').length - line.split('}').length;
}

export function convertAstryxThemeCss(source) {
  const output = [];
  let scopeCount = 0;
  let scopeDepth = 0;

  for (const line of source.split('\n')) {
    if (line.trim() === scopeOpening) {
      if (scopeDepth !== 0) {
        throw new Error('Nested Astryx theme scopes are not supported');
      }

      scopeCount++;
      scopeDepth = 1;
      continue;
    }

    if (scopeDepth === 0) {
      output.push(line);
      continue;
    }

    const trimmedLine = line.trim();
    if (scopeDepth === 1 && trimmedLine === '}') {
      scopeDepth = 0;
      continue;
    }

    let convertedLine = line;
    if (scopeDepth === 1 && trimmedLine !== '') {
      const selector = trimmedLine.startsWith(':scope')
        ? trimmedLine.replace(':scope', scopeSelector)
        : `${scopeSelector} ${trimmedLine}`;
      convertedLine = `  ${selector}`;
    }

    output.push(convertedLine);
    scopeDepth += braceDelta(line);
  }

  if (scopeDepth !== 0) {
    throw new Error('Unclosed Astryx theme scope');
  }
  if (scopeCount === 0) {
    throw new Error('No Astryx vivid theme scopes were found');
  }

  const convertedBody = output.join('\n');
  if (
    convertedBody.includes('@scope') ||
    convertedBody.includes(':scope') ||
    !convertedBody.includes(`${scopeSelector} {`) ||
    !convertedBody.includes(`${scopeSelector} .astryx-button.destructive`)
  ) {
    throw new Error('Astryx vivid theme conversion is incomplete');
  }

  return `${generatedHeader}${convertedBody}`;
}

export async function prepareAstryxTheme() {
  const cliBin = localRequire.resolve('@astryxdesign/cli');
  execFileSync(
    process.execPath,
    [
      cliBin,
      'theme',
      'build',
      'src/themes/vividTheme.ts',
      '--out',
      'src/themes/vivid/vivid.css',
    ],
    { cwd: projectDirectory, stdio: 'inherit' },
  );

  const source = await readFile(builtThemePath, 'utf8');
  const converted = convertAstryxThemeCss(source);
  let current = '';

  try {
    current = await readFile(generatedThemePath, 'utf8');
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }

  if (current === converted) return;

  await mkdir(dirname(generatedThemePath), { recursive: true });
  await writeFile(generatedThemePath, converted, 'utf8');
}

const isMainModule =
  process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isMainModule) {
  prepareAstryxTheme().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
