#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
TOTAL_MINUTES=35
ENV_FILE="${ENV_FILE:-.env.submit}"

banner "Lightling Firefox Add-ons publishing"

stage "Build Firefox review packages" 12
say "Build the listed Firefox artifact and the human-readable source archive AMO reviews."
if ! grep -q '"data_collection_permissions"' src/manifest.json; then
  warn "src/manifest.json is not AMO-ready: data_collection_permissions is missing."
  exit 1
fi
if [[ ! -f STORE.md || ! -f docs/Privacy.md ]]; then
  warn "STORE.md or docs/Privacy.md is missing."
  exit 1
fi
if confirm "Build fresh Firefox and source archives now?"; then
  npm install
  if [[ ! -f thirdparty/bergamot/build/bergamot-translator-worker.wasm ]]; then
    [[ -f .env ]] || cp .env.example .env
    make buildThirdparty
  fi
  npm run build:variant -- firefox-standalone
  npx web-ext build \
    --source-dir build/firefox-standalone \
    --artifacts-dir build \
    --filename firefox-standalone.zip \
    --overwrite-dest
  rm -f build/lightling-source.zip
  git archive --format=zip --output=build/lightling-source.zip HEAD
  say "Created build/firefox-standalone.zip and build/lightling-source.zip."
else
  note "Build later with: npm run build:variant -- firefox-standalone"
  note "Then package it with web-ext build and create a source archive with git archive."
fi
pause "Confirm both ZIP files exist before continuing."

stage "Create the AMO developer account" 5
say "Firefox Add-ons is free, but the API page stays locked until you accept the Distribution Agreement."
open_url "https://addons.mozilla.org/developers/"
step "Sign in with your Mozilla account."
step "Open the Developer Hub and accept the Firefox Add-on Distribution Agreement."
pause "Press Enter after the agreement is accepted."

stage "Create the listed Lightling submission" 8
warn "This creates a public AMO listing and starts Mozilla's review process."
if ! confirm "Continue with the first listed submission?"; then
  warn "Stopped before creating the public listing."
  exit 0
fi
open_url "https://addons.mozilla.org/developers/addon/submit/distribution"
step "Choose distribution 'On this site' (listed), not self-distribution."
step "Upload build/firefox-standalone.zip as the extension package."
step "When source is requested, upload build/lightling-source.zip."
step "Use STORE.md for the listing, privacy disclosure, permission justifications, reviewer notes, and release notes."
step "Set the privacy policy URL to https://github.com/hewel/lightling/blob/master/docs/Privacy.md."
step "Submit the version for review, then open its Developer Hub page."
pause "Press Enter when the add-on page is available."

stage "Record the Firefox Add-on GUID" 2
say "The listed add-on must keep one stable GUID across every future version."
step "On the Developer Hub page, copy the Add-on ID/GUID."
ask FIREFOX_EXTENSION_ID "Paste the Add-on GUID:"
write_env FIREFOX_EXTENSION_ID "$FIREFOX_EXTENSION_ID"
set_var FIREFOX_EXTENSION_ID "$FIREFOX_EXTENSION_ID"
EXPECTED_FIREFOX_EXTENSION_ID="{33b518c2-1f65-4090-8d94-e0a432ebbfd4}"
if [[ "$FIREFOX_EXTENSION_ID" != "$EXPECTED_FIREFOX_EXTENSION_ID" ]]; then
  warn "The AMO GUID differs from Lightling's build ID $EXPECTED_FIREFOX_EXTENSION_ID."
  SKIPPED+=("Update firefoxStandaloneId in scripts/buildExtensionVariant.mjs before submitting another version")
fi

stage "Create and save AMO API credentials" 5
say "These account-wide credentials let GitHub Actions submit future listed versions."
open_url "https://addons.mozilla.org/developers/addon/api/key/"
step "Choose Generate new credentials."
step "Copy the JWT issuer/API key and the JWT secret. The secret is shown once."
ask_secret AMO_KEY "Paste the JWT issuer/API key:"
ask_secret AMO_SECRET "Paste the JWT secret:"
write_env AMO_KEY "$AMO_KEY"
write_env AMO_SECRET "$AMO_SECRET"
set_secret AMO_KEY "$AMO_KEY"
set_secret AMO_SECRET "$AMO_SECRET"

stage "Review publication state" 3
open_url "https://addons.mozilla.org/developers/addons"
step "Confirm Lightling shows the submitted version and its current review state."
say "A successful upload means queued for Mozilla review; it is not live until AMO approves it."
say "Future stable version tags run the listed AMO submission in .github/workflows/release.yml."
say "Prerelease tags remain GitHub-only so beta builds cannot overwrite the public listing accidentally."
pause "Press Enter to finish."

finish