/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/vividTheme.ts
 * Command: astryx theme build src/themes/vividTheme.ts --out src/themes/vivid/vivid.css
 * CLI: @astryxdesign/cli@0.4.3
 * Core: @astryxdesign/core@0.4.3
 */

/// <reference path="./vivid.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const vividTheme: DefinedTheme;
