/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/vividTheme.ts
 * Command: astryx theme build src/themes/vividTheme.ts --out src/themes/vivid/vivid.css
 * CLI: @astryxdesign/cli@0.4.3
 * Core: @astryxdesign/core@0.4.3
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
